apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  containers:
    - name: http-server
      image: hatappi/k8s-training:v1.0
      # command: ["http-server"]
      args: ["http-server"]
      ports:
      - containerPort: 8080
