apiVersion: v1
kind: Namespace
metadata:
  name: q1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-server
  name: http-server
  namespace: q1
spec:
  containers:
    - name: http-server
      image: hatappi/k8s-training:v1.0
      # command: ["http-server"]
      args: ["http-server"]
      ports:
      - containerPort: 8888
